### PR TITLE
build for apple m1

### PR DESCRIPTION
**Pull request by dissy123**
hey, 

just made a build script for M1 chip, I have no clue how to integrate it in your build process :/
so I just added it to the repo  

lg matthias

### CODE REVIEW

**Comment by SebastianStehle** [comment]
There are a lot of changes, very likely due to reformatting. But this makes a review harder

**Comment by dissy123** [comment]
> There are a lot of changes, very likely due to reformatting. But this makes a review harder

will push it again next week and integrate it in the github actions, but i didn't found a way to check it before via github actions?

**Comment by SebastianStehle** [comment]
Just fork  it and run the actions on your own fork. You have to set a tag to run them.

**Comment by dissy123** [comment]
Ah thank you Sebastian, now I understand ;) 
tried to run the job but it fails on  

https://github.com/dissy123/squidex-samples/actions/runs/3937918884

image

**Pull request closed without merging**
