### PR TITLE
CLI sync in | Added field rules support

### PR DESCRIPTION
**Pull request by jagat2189**

### CODE REVIEW

**Comment by SebastianStehle** [comment]
Thank you very much, but I think this should be done on the API Side. It is actually already done there, so the question is: why does it not work: https://github.com/Squidex/squidex/blob/master/backend/src/Squidex.Domain.Apps.Core.Operations/EventSynchronization/SchemaSynchronizer.cs#L78

**Comment by jagat2189** [comment]
I think when we go for sync in command, it is internally using upsertschemadto.cs https://github.com/Squidex/squidex/blob/master/backend/src/Squidex/Areas/Api/Controllers/Schemas/Models/UpsertSchemaDto.cs

This dto do not have field rules property so while mapping from CLI, it looses all field rules.

**Comment by jagat2189** [comment]
I think SchemaSynchroniser.cs file changes are not required. but we require generated.cs file changes as it should contain UpsertSchemaDto.cs field rules changes. and then everything will be handled at API side.

**Comment by SebastianStehle** [comment]
I have merged your change it, thank you very much. I think you just have to run the code generator now and then it should work. Awaiting your PR (testing).

**Comment by jagat2189** [comment]
I have tested the changes after generating the code, its working fine. And client library is referred as nuget package in CLI that means should client library be published as nuget package?

**Comment by SebastianStehle** [comment]
Yes, i

**Pull request merged**
