### PR TITLE
Microsoft.Extensions.Caching.Memory is causing problems with .NET Sta…

### PR DESCRIPTION
**Pull request by Jaben**
…ndard 2.0 targets due to it being a .NET 5 dependency. Added back multi-targetting to so it doesn't break our .NET Core 2.2. dependencies.

### CODE REVIEW

**Comment by Jaben** [comment]
Hey @SebastianStehle  -- this caused a lot of problems with one of our dependencies since it has to stay .NET v4.71 -- and .NET Standard 2.0 at that level is very touchy. Adding that Microsoft.Extensions.Caching.Memory of 5.0 makes the newer squidex nugets unusable for us -- it won't run against .NET 4.7.1. This fixes it.

**Comment by SebastianStehle** [comment]
Thank you very much.

**Comment by Jaben** [comment]
@SebastianStehle Absolutely -- thank you!!

**Comment by SebastianStehle** [comment]
Unfortunanetaly it does not build.

**Comment by SebastianStehle** [comment]
https://github.com/Squidex/squidex-samples/actions/runs/768196313

**Comment by Jaben** [comment]
> 
> 
> https://github.com/Squidex/squidex-samples/actions/runs/768196313

Fix is here: https://github.com/Squidex/squidex-samples/pull/59 -- Sorry about that.

**Pull request merged**
