### PR TITLE
Refactor codegeneration

### PR DESCRIPTION
**Pull request by Liebeck**
I refactored CodeGeneration into a separate class and updated the README.md based on my difficulty to get started with Squidex.ClientLibrary and the advice I gave on https://support.squidex.io/t/insert-blog-in-project/1711

### CODE REVIEW

**Comment by SebastianStehle** [comment]
I would make a separate class library for the code generator to put it to Nuget.

**Comment by Liebeck** [comment]
Yes, sounds good.

Or just include it into the ClientLibrary. That way, it can be used from within the project you are using the auto generated classes anyway.

(While you are at it, think about https://support.squidex.io/t/move-squidex-clientlibrary-into-separate-repository/1639 :))

**Comment by SebastianStehle** [comment]
I don't want to have the NSwag dependency in the client library.

**Comment by Liebeck** [comment]
Hmm, okay.
Then one repository `Squidex.ClientLibrary` with three projects
- Squidex.ClientLibrary
- Squidex.ClientLibrary.Tests
- Squidex.ClientLibrary.CodeGeneration

and two NuGet packages
- Squidex.ClientLibrary
- Squidex.ClientLibrary.CodeGeneration
?

**Comment by SebastianStehle** [comment]
We will deal about the repository, I promise, but not now. It is 99.9% me who works on them and I don't want to checkout 20 repositories.

We would  need a fourth project, because Squidex.ClientLibrary.CodeGeneration is the class library and also the console application.

We should also use a CodeGenerationOptions class instead of the three parameters as it is easier to extend it. I made the mistake with the SquidexClientManager

**Comment by Liebeck** [comment]
> We will deal about the repository, I promise, but not now. It is 99.9% me who works on them and I don't want to checkout 20 repositories.

Okay ;-)

> We would need a fourth project, because Squidex.ClientLibrary.CodeGeneration is the class library and also the console application.

I would make it a class library and just call it from the web application. The call anywhere in the ASP.NET Core MVC application, e.g., in a controller method that's placed inside a `#if DEBUG` preprocessor directive.

> We should also use a CodeGenerationOptions class instead of the three parameters as it is easier to extend it. I made the mistake with the SquidexClientManager
Okay, I'll refactor it and push another commit

**Comment by SebastianStehle** [comment]
But I use Squidex.ClientLibrary.CodeGeneration when I publish a new version of the client library, so I need a ConsoleApplication for that.

**Comment by Liebeck** [comment]
Ah okay, so it's part of your CI/CD pipeline?

**Comment by SebastianStehle** [comment]
Not really, I just run it locally.

**Comment by Liebeck** [comment]
@SebastianStehle  Have you given any thought about cherry-picking https://github.com/Squidex/squidex-samples/pull/39/commits/b44b4f38dd4c7e639f41f551ba6e1e3e5191363e ?

**Comment by SebastianStehle** [comment]
I have another look the next days. Can you fix the conflict?

**Pull request closed without merging**
