### PR TITLE
Update ContentsClient.cs

### PR DESCRIPTION
**Pull request by TheUltimateC0der**
I added `OrderBy = "id"` as default to remove the need for the `added` HashSet<string> to check for duplicate items. This orders the items by `id` per default so we dont have to do it serverside.

I also changed the `do..while` to `while` in order to prevent any request from being sent before stopping.

I also simplyfied the way `query.Skip` is calculated

### CODE REVIEW

**Comment by TheUltimateC0der** [comment]
I also thought about being able to set the `OrderBy` with an optional parameter which defaults to `"id"`. Would that be a good idea @SebastianStehle ?

**Comment by SebastianStehle** [comment]
To be honest: I don't like the idea.

If you skip the result, I would like to get a result that makes most sense and his is lastModified Desc. I also do not want to add a breaking change, but you can provide another method or make the sorting configurable. But sorting by id does not get rid of the HashSet, because the ids in Squidex are random values (Guid) and not auto incremented integer. So you need natural sorting (by insert time) and this is currently not possible.

Btw: I think it needs to be `id asc` or `id desc`, but not 100% sure.

**Comment by TheUltimateC0der** [comment]
>To be honest: I don't like the idea.

Okay. Np 😄 

>Btw: I think it needs to be id asc or id desc, but not 100% sure.

Nope. I tested it exactly like this, and it works.

Currently, if you don´t add any `OrderBy`, the `GetAllAsync` function will NOT return ALL results. This PR is a simple fix for this bug. You can test this behavior with this code

```csharp
var dataIPullFromSomeService = new List<string>(); //This is the data that gets pulled from another service
for (int i = 0; i < 199; i++) //For demo we just add this
{
    dataIPullFromSomeService.Add($"Data:{i}"); 
}

//We get all existing data from our Squidex instance with this in pages of 10 items
await _someContentsClient.GetAllAsync(10, async item =>
{
   //We simply check if the item we iterate though from our api, exists in the data from our service
    var listItem = dataIPullFromSomeService.FirstOrDefault(x => x == item.Data.Name);
    if (listItem != null) //If the item already exists
    {
        dataIPullFromSomeService.Remove(listItem); //We delete it from the list
    }
});

//Since there is only the data left, that should not exist in our Squidex instance, we add all items to our Squidex instance that are left in the list
foreach (var s in dataIPullFromSomeService)
{
    await _someContentsClient.CreateAsync(new SomeData{ Name = s }, true);
}
```

`dataIPullFromSomeService` will still have items, even tho there should ne none left when executing `foreach (var s in dataIPullFromSomeService)`

This will execute fine on the first time, since there are no items in Squidex. Execute it the second time, and you will be greeted by an `Squidex.ClientLibrary.SquidexException` which tells you 
```
Squidex Request failed: {"message":"Validation error","traceId":"|cdca0dc4-4bf33652ed95df12.","type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","details":["name: Another content with the same value exists.","name: Another content with the same value exists."],"statusCode":400}
```

I also debugged the function, and there are alot of items already added to the `added` HashSet. My schama I tested it with has 2053 items in it, which had around 106 times where there has been an item already added with the same key to the HashSet. And at the end, the HashSet only had 2047, so a difference of -6 items in it.

**Comment by SebastianStehle** [comment]
If you can provide a solution that works with different sortings it would be the best and I would really appreciate it.

I also have a test suite that I run with every build: https://github.com/Squidex/squidex/blob/master/backend/tools/TestSuite/TestSuite.ApiTests/ContentQueryTests.cs

So my preferred solution would be:

1. Fix the current implementation
2. Provide an overload with custom sorting
3. Add a test to the test suite.

the test suite is using the nuget version, you can just temporarily add the client library to the project directly and reference this instead.

**Comment by TheUltimateC0der** [comment]
I have the feeling you mix things up, or there is some kind of misunderstanding here.

My PR is only to fix the bug, and not to provide any extra feature. Maybe that was not clear re-reading the first comment myself.

Please use the code I provided above to reproduce the issue mentioned.

**Comment by SebastianStehle** [comment]
Yes, I know.

I understand the issue now and your fix is correct. Sorry!

The issue is that you are inserting a lot of items in a short time, therefore the creation or update time of some of these entries is the same, so basically you have something like this

ID | Time
1  | 12:01 AM
2  | 12:01 AM
3  | 12:01 AM
4  | 12:02 AM
5  | 12:02 AM

And therefore when you sort by time the result can be either 1,2,3,4,5 or 3,2,1,5,4 or 3,1,2,4,5 or ... the sort order is just not defined.

When you sort by id, the values are different obviously. The question is: Is the query satisfied by an index? I have to check this first, before I merge the PR, otherwise it could fail when you have a large amount of entities.

**Pull request closed without merging**
